name = "stafford-group-associates"
main = "worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[vars]
# Environment variables will be set via Cloudflare Dashboard or CLI
# RESEND_API_KEY (secret)
# TURNSTILE_SECRET_KEY (secret)
