name = "contact-handler"
main = "index.ts"
compatibility_date = "2024-01-01"

[vars]
# Environment variables will be set via Cloudflare Dashboard or CLI
# RESEND_API_KEY (secret)
# TURNSTILE_SECRET_KEY (secret)
